### ISSUE TITLE
OpenMP parallelization improvements

### ISSUE THREAD

**Issue by tjof2** [tjof2/pgure-svt#31]
Parallelization over frames / frame blocks would be better than the current inner-loop implementation.

**Comment by tjof2** [comment]
Also figuring out the best way to run on distributed computing architectures. MPI or an alternative?

**Comment by hentr** [comment]
yeah, I just tested with an 4core/8thread intel i7-6700 @3.4GHz, 512x512 sized frames.

2 threads: 36 sec/fr
4 threads: 30 sec/fr
8 threads: 27 sec/fr

So there's a good room for improvement, is this something that is not too much work? 
I guess this would be in the C++ part of the code, not python

**Comment by tjof2** [comment]
I think its a case of commenting out 
- https://github.com/tjof2/pgure-svt/blob/master/src/svt.hpp#L129
- https://github.com/tjof2/pgure-svt/blob/master/src/svt.hpp#L165

And adding in the OpenMP `#pragma` here:
- https://github.com/tjof2/pgure-svt/blob/master/src/lib-PGURE-SVT.cpp#L161

**But** this approach would need to take care over: 
- https://github.com/tjof2/pgure-svt/blob/master/src/lib-PGURE-SVT.cpp#L232

To avoid competing threads from trying to overwrite the same frame.
