### ISSUE TITLE
"error: Mat::operator(): index out of bounds"

### ISSUE THREAD

**Issue by hentr** [tjof2/pgure-svt#34]
Along with a "OSError: [WinError -529697949] Windows Error 0xe06d7363" output in the notebook. Anyway, seems to be the c++ code failing, not the python, so its a good bit less transparent. 

On every few image series I have been denoising I have gotten this error in the jupyther notebook terminal window. Have not really been a problem, except now with the latest batch of really good data, almost half the series are failing, so I have to get it fixed. 

Previously it seems to have come from 1) some series with corrupt data at late frames (recording error), while 2) some recordings I cannot find anything wrong with, where some it works if I rerun, while others never work. These latest, though seems to be mostly of the 2) type.

 Any idea how to attack it? 

edit: OSError

**Comment by hentr** [comment]
Also, threw this error when it just now ran out of memory (my fault, well PGURE-SVT does take a lot of RAM on large datasets), so it is a quite general, not very informative error...

Is it at least easy to get it to dump to a file which frame it is at when it fails? I am looping over many image series, so the output in the notebook terminal gets written over after a while. 

Edit: no, wait, the memory error was from a different notebook :)

**Comment by hentr** [comment]
At least one of the failed series have at least one completely or partially black frame (but otherwise non-corrupt and readable), due to blanking the beam right before the series stops (which I do to avoid shooting apart what I am imaging). Does this create a too abrupt change between frames, or so?

**Comment by tjof2** [comment]
`error: Mat::operator(): index out of bounds` is exactly that, it's trying to access a matrix element that doesn't exist. 

> "At least one of the failed series have at least one completely or partially black frame[...]Does this create a too abrupt change between frames, or so?"

This may not help, but I don't think it's the problem.

- Are the images definitely square? 
- What are the dimensions?
- What are the patchsize dimensions?

Does `patchsize / image dimensions = an integer`?

Looking at http://tjof2.github.io/pgure-svt/python.html, have you also tried:
- `patchoverlap` - Step size in pixels by which successive spatial patches are displaced with respect to one another. _try setting this to 0.5 * patchsize_
- `length` - Length in frames of a temporal block (**must be odd**) _it's definitely odd right?_
- `optimize` - Turn on (True) or off (False) optimisation of lambda with PGURE (if False, threshold must be specified) _try specifying an arbitrary threshold to speed up the testing_
