### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by ericpre** [tjof2/pgure-svt#47]
It would be good to package pgure-svt on conda-forge.

**Comment by tjof2** [comment]
Yeah, same for pypi too.

I'm aware that there's a little bit more work involved due to the C++ compiler and additional libraries. Some combination of manylinux images and auditwheel I think, but I've not looked that long at it.

**Comment by ericpre** [comment]
For the conda-forge package, see work in progress https://github.com/conda-forge/staged-recipes/pull/12037. At the moment, it works only on Linux and MacOSX

I had to made a patch (remove `setup_requires` in `setup.py`) to make it work with conda-build.

**Comment by tjof2** [comment]
> At the moment, it works only on Linux and MacOSX

That's fine for now - Windows was horrible to get right the first time round (~4 years ago).

> I had to made a patch (remove setup_requires in setup.py) to make it work with conda-build.

Also fine - it was a copy-paste thing anyway. I've removed it from `master`.

**Comment by ericpre** [comment]
Great! On the topic of packaging: #49

**Comment by tjof2** [comment]
Worth noting that any package build probably needs to exclude `"-march=native"` from the Cython compilation:
https://github.com/tjof2/pgure-svt/blob/ebc7b86673e149fb2f23f50d300fa2f784e77095/setup.py#L9-L28

**Comment by ericpre** [comment]
Indeed, conda-forge uses `-march=nocona` and this flag most likely get overwritten. Do you prefer to patch it when packaging on conda-forge and keep the `-march=native` here?

Maybe, one way to sort out the windows build is to use cmake for the python package too? Prismatic is a good example:
- https://github.com/prism-em/prismatic (the [dev branch](https://github.com/prism-em/prismatic/tree/dev) has the changes required for conda-forge)
- https://github.com/conda-forge/prismatic_split-feedstock/blob/master/recipe/build_pyprismatic.sh

**Comment by tjof2** [comment]
> Do you prefer to patch it when packaging on conda-forge and keep the -march=native here?

The best thing would be to profile whether or not it makes a difference (I suspect it might). But if patching isn't difficult, that's the next best thing.

**Comment by tjof2** [comment]
And yes cmake is probably the way to go (indeed that's what it used until I switched to cython as the wrapper for "simplicity")

**Comment by ericpre** [comment]
https://github.com/conda-forge/staged-recipes/pull/12037 have been merged, I will check later when it is available on anaconda cloud in 1 or 2 hours and update the installation instructions accordingly.

**Comment by ericpre** [comment]
The conda-forge feedstock lives in https://github.com/conda-forge/pgure-svt-feedstock.
