### ISSUE TITLE
Error example

### ISSUE THREAD

**Issue by ericpre** [tjof2/pgure-svt#50]
When building using conda-build, the example of `README.md` raises an error:
```python
import numpy as np
from pguresvt import pguresvt

# Example dataset has dimensions (nx, ny, T),
# in this case a 128x128px video with 25 frames
X = np.random.randn(128, 128, 25)

# Initialize the algorithm
# with default parameters
svt = pguresvt.SVT()

# Run the algorithm on the data X
svt.denoise(X)
```

```
error: 
error: Mat::operator(): index out of boundsMat::operator(): index out of bounds

terminate called after throwing an instance of 'std::logic_error'
terminate called recursively
  what():  Mat::operator(): index out of bounds
```

The test suite works fine.

**Comment by ericpre** [comment]
Thanks for the quick fix, this is working now!

This example use a single core, is multi-threading supported? I am wondering if this is due to the libraries I am using (all from conda-forge)?

**Comment by tjof2** [comment]
@ericpre yes multithreading is supported with the `n_jobs` argument. The error was caused by a long-standing bug from years ago.

**Comment by ericpre** [comment]
Indeed, using this argument works perfectly. Would it make sense to have `-1` as default or `None` using all available resources?

**Comment by tjof2** [comment]
I've updated the default to use all available resources, as well as a few other obvious bugs I never fixed :)
